/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir_warmad;

import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import java.awt.Font;
import javax.swing.UIManager;
import kasir_warmad.tampilan.tambah_barang;
import kasir_warmad.tampilan.tambah_stok;
import javax.swing.table.DefaultTableModel;
import kasir_warmad.tampilan.tambah_barang;
import kasir_warmad.tampilan.tambah_stok;
import java.sql.Connection;
import kasir_warmad.Dashboard;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import kasir_warmad.sistem.Koneksi;
import desain.GradientPanel;
import javax.swing.JFrame;
import kasir_warmad.sistem.Session;
import utils.RupiahUtil;

/**
 *
 * @author ThinkPad
 */
public class Kelola_barang extends javax.swing.JFrame {

    /**
     * Creates new form Kelola_Barang
     */
    public Kelola_barang() {
        initComponents();
    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        System.out.println("setVisible dipanggil dengan b = " + b);
        if (b) {
            initialize();
        }
    }

    private void initialize() {
        System.out.println("initialize dipanggil");
        refreshTable();
    }

    public void refreshTable() {
        // Definisikan kolom untuk tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nama Barang");
        model.addColumn("Kategori");
        model.addColumn("Stok");
        model.addColumn("Harga Jual");
        model.addColumn("Tanggal Kadaluarsa");

        // Set model ke tabel
        TabelK.setModel(model);

        try {
            Connection conn = Koneksi.getKoneksi();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Koneksi ke database gagal!");
                return;
            }
            System.out.println("Koneksi ke database berhasil");
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM v_stok");

            int rowCount = 0;
            while (rs.next()) {
                Object[] row = {
                    rs.getString("nama_barang"),
                    rs.getString("kategori_barang"),
                    rs.getInt("jumlah_stok"),
                    RupiahUtil.format(rs.getBigDecimal("harga_jual")), // Asumsi RupiahUtil ada
                    rs.getString("tanggal_kadaluarsa")
                };
                model.addRow(row);
                rowCount++;
            }
            System.out.println("Jumlah baris yang dimuat ke tabel: " + rowCount);
            if (rowCount == 0) {
                JOptionPane.showMessageDialog(this, "Tidak ada data di view v_stok. Tambahkan stok untuk melihat data di tabel.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data tabel: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelutamaK = new GradientPanel();
        TambahbarangK = new javax.swing.JButton();
        TambahstokK = new javax.swing.JButton();
        TbarangterlarisK = new javax.swing.JScrollPane();
        TabelK = new javax.swing.JTable();
        panelluarK = new java.awt.Panel();
        DashboardK = new javax.swing.JButton();
        LupdatestokK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelutamaK.setBackground(new java.awt.Color(255, 255, 255));

        TambahbarangK.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        TambahbarangK.setText("Tambah Barang+");
        TambahbarangK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahbarangKActionPerformed(evt);
            }
        });

        TambahstokK.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        TambahstokK.setText("Tambak Stok+");
        TambahstokK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahstokKActionPerformed(evt);
            }
        });

        TabelK.setFont(new java.awt.Font("Poppins", java.awt.Font.BOLD, 14)
        );
        TabelK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TbarangterlarisK.setViewportView(TabelK);

        DashboardK.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        DashboardK.setText("Dashboard");
        DashboardK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelluarKLayout = new javax.swing.GroupLayout(panelluarK);
        panelluarK.setLayout(panelluarKLayout);
        panelluarKLayout.setHorizontalGroup(
            panelluarKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelluarKLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DashboardK)
                .addGap(89, 89, 89))
        );
        panelluarKLayout.setVerticalGroup(
            panelluarKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelluarKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LupdatestokK.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        LupdatestokK.setForeground(new java.awt.Color(255, 255, 255));
        LupdatestokK.setText("Update Barang ");

        javax.swing.GroupLayout panelutamaKLayout = new javax.swing.GroupLayout(panelutamaK);
        panelutamaK.setLayout(panelutamaKLayout);
        panelutamaKLayout.setHorizontalGroup(
            panelutamaKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelluarK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelutamaKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TbarangterlarisK)
                .addContainerGap())
            .addGroup(panelutamaKLayout.createSequentialGroup()
                .addGroup(panelutamaKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelutamaKLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(TambahbarangK)
                        .addGap(116, 116, 116)
                        .addComponent(TambahstokK))
                    .addGroup(panelutamaKLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(LupdatestokK, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(142, 834, Short.MAX_VALUE))
        );
        panelutamaKLayout.setVerticalGroup(
            panelutamaKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelutamaKLayout.createSequentialGroup()
                .addComponent(panelluarK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(panelutamaKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TambahbarangK)
                    .addComponent(TambahstokK))
                .addGap(46, 46, 46)
                .addComponent(LupdatestokK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TbarangterlarisK, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutamaK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutamaK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TambahbarangKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahbarangKActionPerformed
        tambah_barang tb = new tambah_barang(new JFrame(), true, this);
        tb.setVisible(true);
        tb.pack();
        tb.setLocationRelativeTo(null);

    }//GEN-LAST:event_TambahbarangKActionPerformed

    private void DashboardKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardKActionPerformed
        String role = Session.getCurrentUserRole();
        Dashboard da = new Dashboard(role);
        da.setVisible(true);
        da.pack();
        da.setLocationRelativeTo(null);
        dispose();

    }//GEN-LAST:event_DashboardKActionPerformed

    private void TambahstokKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahstokKActionPerformed
        tambah_stok tb = new tambah_stok(new JFrame(), true, this);
        tb.setVisible(true);
        tb.pack();
        tb.setLocationRelativeTo(null);
        refreshTable();
    }//GEN-LAST:event_TambahstokKActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatArcOrangeIJTheme());
            UIManager.put("Button.arc", 999);
            UIManager.put("defaultFont", new Font("Poppins", Font.BOLD, 14));

        } catch (Exception ex) {
            System.err.println("Gagal mengatur tema FlatLaf Arc Orange.");
            ex.printStackTrace();
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kelola_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DashboardK;
    private javax.swing.JLabel LupdatestokK;
    private javax.swing.JTable TabelK;
    private javax.swing.JButton TambahbarangK;
    private javax.swing.JButton TambahstokK;
    private javax.swing.JScrollPane TbarangterlarisK;
    private java.awt.Panel panelluarK;
    private javax.swing.JPanel panelutamaK;
    // End of variables declaration//GEN-END:variables
}
