/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir_warmad;

import java.sql.*;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import kasir_warmad.sistem.Koneksi;
import kasir_warmad.sistem.Session;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import utils.RupiahUtil;

/**
 *
 * @author Ariel
 */
public class Laporan extends javax.swing.JFrame {

    /**
     * Creates new form laporan
     */
    public Laporan() {
        initComponents();
    }

    public void cetakLaporanPenjualan(int bulan, int tahun) {
        try {
            Connection conn = Koneksi.getKoneksi();
            // Path ke file .jasper (hasil compile dari .jrxml)
            String reportPath = "src/reports/LaporanPenjualan.jasper";

            // Load report dari file .jasper
            JasperReport jasperReport = (JasperReport) JRLoader.loadObjectFromFile(reportPath);

            // Parameter untuk report
            Map<String, Object> parameters = new HashMap<>();
            parameters.put("bulan", bulan);
            parameters.put("tahun", tahun);

            // Fill report dengan data
            JasperPrint jasperPrint = JasperFillManager.fillReport(
                    jasperReport,
                    parameters,
                    conn
            );

            // Tampilkan preview report
            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setTitle("Laporan Penjualan Bulanan");
            viewer.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Error saat membuat report: " + e.getMessage(),
                    "Report Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new desain.GradientPanel();
        pilihTahunBulanJC = new com.toedter.calendar.JDateChooser();
        tampilkanBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableL = new javax.swing.JTable();
        cetakBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pilihTahunBulanJC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tampilkanBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tampilkanBtn.setText("TAMPILKAN");
        tampilkanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilkanBtnActionPerformed(evt);
            }
        });

        tableL.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableL);

        cetakBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cetakBtn.setText("CETAK LAPORAN");
        cetakBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(pilihTahunBulanJC, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tampilkanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cetakBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1044, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tampilkanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pilihTahunBulanJC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cetakBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cetakBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakBtnActionPerformed
        // Tampilkan dialog konfirmasi
        int cetak = JOptionPane.showConfirmDialog(null, "Cetak laporan penjualan sekarang?", "Cetak Laporan", JOptionPane.YES_NO_OPTION);
        if (cetak == JOptionPane.YES_OPTION) {
            // Ambil tanggal dari pilihTahunBulanJC
            java.util.Date selectedDate = pilihTahunBulanJC.getDate();
            if (selectedDate == null) {
                JOptionPane.showMessageDialog(this, "Silakan pilih tanggal terlebih dahulu.");
                return;
            }

            // Ekstrak bulan dan tahun
            Calendar cal = Calendar.getInstance();
            cal.setTime(selectedDate);
            int bulan = cal.get(Calendar.MONTH) + 1; // bulan dimulai dari 0
            int tahun = cal.get(Calendar.YEAR);

            // Panggil metode cetakLaporanPenjualan
            reports.Laporan laporan = new reports.Laporan(); // Asumsikan kelas ini ada
            laporan.cetakLaporanPenjualan(bulan, tahun);
        }
    }//GEN-LAST:event_cetakBtnActionPerformed

    private void tampilkanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilkanBtnActionPerformed
        // TODO add your handling code here:
        java.util.Date selectedDate = pilihTahunBulanJC.getDate();
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Silakan pilih tanggal terlebih dahulu.");
            return;
        }

        Calendar cal = Calendar.getInstance();
        cal.setTime(selectedDate);
        int bulan = cal.get(Calendar.MONTH) + 1; // bulan dimulai dari 0
        int tahun = cal.get(Calendar.YEAR);

        // Set kolom tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nama Barang");
        model.addColumn("Total Terjual");
        model.addColumn("Total Harga Beli");
        model.addColumn("Total Pendapatan");
        model.addColumn("Laba Kotor");

        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/kasir_warmad", "root", ""); PreparedStatement stmt = conn.prepareStatement(
                "SELECT bj.nama_barang, "
                + "SUM(dtp.jumlah) AS total_terjual, "
                + "SUM(dtp.jumlah * sg.harga_beli) AS total_harga_beli, "
                + "SUM(dtp.subtotal) AS total_pendapatan, "
                + "SUM(dtp.subtotal) - SUM(dtp.jumlah * sg.harga_beli) AS laba_kotor "
                + "FROM detail_transaksi_pelanggan dtp "
                + "JOIN transaksi_kasir tk ON dtp.id_transaksi_kasir = tk.id_transaksi_kasir "
                + "JOIN barang_jual bj ON dtp.id_barang_jual = bj.id_barang_jual "
                + "JOIN stok_gudang sg ON dtp.id_barang_jual = sg.id_barang_jual "
                + "WHERE MONTH(tk.tanggal) = ? AND YEAR(tk.tanggal) = ? "
                + "GROUP BY bj.nama_barang")) {

            stmt.setInt(1, bulan);
            stmt.setInt(2, tahun);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                Object[] row = {
                    rs.getString("nama_barang"),
                    rs.getInt("total_terjual"),
                    RupiahUtil.format(rs.getBigDecimal("total_harga_beli")),
                    RupiahUtil.format(rs.getBigDecimal("total_pendapatan")),
                    RupiahUtil.format(rs.getBigDecimal("laba_kotor"))
                };
                model.addRow(row);
            }

            tableL.setModel(model);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menampilkan data: " + e.getMessage());
        }
    }//GEN-LAST:event_tampilkanBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String role = Session.getCurrentUserRole();
        Dashboard da = new Dashboard(role);
        da.setVisible(true);
        da.pack();
        da.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cetakBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser pilihTahunBulanJC;
    private javax.swing.JTable tableL;
    private javax.swing.JButton tampilkanBtn;
    // End of variables declaration//GEN-END:variables
}
