/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir_warmad;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import static javax.swing.JOptionPane.showMessageDialog;
import java.sql.*;
import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.UIManager;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author ThinkPad
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        loadRolesToComboBox();

        UsernameR.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PasswordR.requestFocusInWindow();
            }
        });
        PasswordR.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                EmailR.requestFocusInWindow();
            }
        });
        EmailR.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                RfidR.requestFocusInWindow();
            }
        });
        RfidR.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                RegisterR.doClick(); // Seolah klik tombol login
            }
        });
    }

    private void loadRolesToComboBox() {
        String SUrl = "jdbc:mysql://localhost:3306/kasir_warmad";
        String SUser = "root";
        String SPass = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);

            // Ambil distinct role agar pilihan combobox unik
            String query = "SELECT DISTINCT role FROM pengguna_aplikasi";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            RoleR.removeAllItems();  // Kosongkan combobox dulu
            while (rs.next()) {
                RoleR.addItem(rs.getString("role"));
            }
            rs.close();
            ps.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load data role: " + e.getMessage());
        }
    }

    public static boolean isValidEmail(String email) {
        return email.contains("@") && email.contains(".");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        panelluar1R = new javax.swing.JPanel();
        panelluar2R = new javax.swing.JPanel();
        paneldalamR = new javax.swing.JPanel();
        UsernameR = new javax.swing.JTextField();
        EmailR = new javax.swing.JTextField();
        RegisterR = new javax.swing.JButton();
        LregisterR = new javax.swing.JLabel();
        LusernameR = new javax.swing.JLabel();
        LpasswordR = new javax.swing.JLabel();
        LemailR = new javax.swing.JLabel();
        PasswordR = new javax.swing.JPasswordField();
        RfidR = new javax.swing.JTextField();
        LrfidR = new javax.swing.JLabel();
        RoleR = new javax.swing.JComboBox<>();
        LroleR = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        LsdhpunyaakunR = new javax.swing.JLabel();
        TothepageR = new java.awt.Label();
        welcomeR = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1245, 768));

        panelluar1R.setBackground(new java.awt.Color(255, 255, 255));
        panelluar1R.setPreferredSize(new java.awt.Dimension(1245, 768));

        panelluar2R.setBackground(new java.awt.Color(255, 204, 153));
        panelluar2R.setPreferredSize(new java.awt.Dimension(891, 768));

        paneldalamR.setBackground(new java.awt.Color(255, 153, 51));
        paneldalamR.setPreferredSize(new java.awt.Dimension(581, 584));
        paneldalamR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paneldalamRKeyReleased(evt);
            }
        });

        UsernameR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameRActionPerformed(evt);
            }
        });

        EmailR.setBorder(null);
        EmailR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailRActionPerformed(evt);
            }
        });

        RegisterR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        RegisterR.setForeground(new java.awt.Color(255, 153, 51));
        RegisterR.setText("REGISTER");
        RegisterR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterRActionPerformed(evt);
            }
        });

        LregisterR.setBackground(new java.awt.Color(255, 255, 255));
        LregisterR.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        LregisterR.setForeground(new java.awt.Color(255, 255, 255));
        LregisterR.setText("REGISTER");

        LusernameR.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LusernameR.setForeground(new java.awt.Color(255, 255, 255));
        LusernameR.setText("Username");

        LpasswordR.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LpasswordR.setForeground(new java.awt.Color(255, 255, 255));
        LpasswordR.setText("Password");

        LemailR.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LemailR.setForeground(new java.awt.Color(255, 255, 255));
        LemailR.setText("Email");

        RfidR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RfidRActionPerformed(evt);
            }
        });

        LrfidR.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LrfidR.setForeground(new java.awt.Color(255, 255, 255));
        LrfidR.setText("RFID KODE");

        RoleR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        RoleR.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RoleRItemStateChanged(evt);
            }
        });

        LroleR.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LroleR.setForeground(new java.awt.Color(255, 255, 255));
        LroleR.setText("Role");

        javax.swing.GroupLayout paneldalamRLayout = new javax.swing.GroupLayout(paneldalamR);
        paneldalamR.setLayout(paneldalamRLayout);
        paneldalamRLayout.setHorizontalGroup(
            paneldalamRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldalamRLayout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addGroup(paneldalamRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldalamRLayout.createSequentialGroup()
                        .addGroup(paneldalamRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LrfidR)
                            .addComponent(LusernameR)
                            .addComponent(UsernameR, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(LpasswordR)
                            .addComponent(PasswordR)
                            .addComponent(EmailR)
                            .addComponent(LemailR, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RfidR)
                            .addComponent(LroleR)
                            .addComponent(RoleR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldalamRLayout.createSequentialGroup()
                        .addComponent(LregisterR)
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldalamRLayout.createSequentialGroup()
                        .addComponent(RegisterR)
                        .addGap(235, 235, 235))))
        );
        paneldalamRLayout.setVerticalGroup(
            paneldalamRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldalamRLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(LregisterR)
                .addGap(18, 18, 18)
                .addComponent(LusernameR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LpasswordR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LemailR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailR, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LroleR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RoleR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LrfidR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RfidR)
                .addGap(18, 18, 18)
                .addComponent(RegisterR)
                .addGap(47, 47, 47))
        );

        loginBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 153, 51));
        loginBtn.setText("LOGIN");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        LsdhpunyaakunR.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LsdhpunyaakunR.setForeground(new java.awt.Color(255, 255, 255));
        LsdhpunyaakunR.setText("Sudah punya akun ?");

        javax.swing.GroupLayout panelluar2RLayout = new javax.swing.GroupLayout(panelluar2R);
        panelluar2R.setLayout(panelluar2RLayout);
        panelluar2RLayout.setHorizontalGroup(
            panelluar2RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelluar2RLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(panelluar2RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelluar2RLayout.createSequentialGroup()
                        .addComponent(paneldalamR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelluar2RLayout.createSequentialGroup()
                        .addComponent(LsdhpunyaakunR, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        panelluar2RLayout.setVerticalGroup(
            panelluar2RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelluar2RLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(paneldalamR, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelluar2RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn)
                    .addComponent(LsdhpunyaakunR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TothepageR.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        TothepageR.setForeground(new java.awt.Color(255, 153, 0));
        TothepageR.setText("To The Page");

        welcomeR.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        welcomeR.setForeground(new java.awt.Color(255, 153, 0));
        welcomeR.setText("WELCOME");

        javax.swing.GroupLayout panelluar1RLayout = new javax.swing.GroupLayout(panelluar1R);
        panelluar1R.setLayout(panelluar1RLayout);
        panelluar1RLayout.setHorizontalGroup(
            panelluar1RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelluar1RLayout.createSequentialGroup()
                .addGroup(panelluar1RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelluar1RLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(TothepageR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelluar1RLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(welcomeR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 394, Short.MAX_VALUE)
                .addComponent(panelluar2R, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelluar1RLayout.setVerticalGroup(
            panelluar1RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelluar1RLayout.createSequentialGroup()
                .addComponent(panelluar2R, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelluar1RLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(welcomeR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TothepageR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(409, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelluar1R, javax.swing.GroupLayout.DEFAULT_SIZE, 1527, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelluar1R, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paneldalamRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paneldalamRKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String rfid = RfidR.getText().trim();
            if (!rfid.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Kartu RFID terdeteksi: " + rfid);
            }
        }

    }//GEN-LAST:event_paneldalamRKeyReleased

    private void RfidRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RfidRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RfidRActionPerformed

    private void RegisterRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterRActionPerformed
// Variabel koneksi
        String email, username, password, rfid, role, query;
        String SUrl = "jdbc:mysql://localhost:3306/kasir_warmad";
        String SUser = "root";
        String SPass = "";

// Ambil data dari form
        email = EmailR.getText().trim();
        username = UsernameR.getText().trim();
        password = PasswordR.getText().trim();
        rfid = RfidR.getText().trim();
        role = (String) RoleR.getSelectedItem(); // ambil role dari combobox

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);

            if (email.isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Email is required", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (!isValidEmail(email)) {
                JOptionPane.showMessageDialog(new JFrame(), "Invalid email format", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (username.isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Username is required", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (password.isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Password is required", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (rfid.isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "RFID is required", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                // Cek RFID
                String checkSQL = "SELECT * FROM pengguna_aplikasi WHERE rfid_kode = ?";
                PreparedStatement checkStmt = con.prepareStatement(checkSQL);
                checkStmt.setString(1, rfid);
                ResultSet rs = checkStmt.executeQuery();

                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "RFID sudah terdaftar!", "Gagal", JOptionPane.ERROR_MESSAGE);
                    rs.close();
                    checkStmt.close();
                } else {
                    rs.close();
                    checkStmt.close();

                    // Cek Username
                    String checkUserSQL = "SELECT * FROM pengguna_aplikasi WHERE username = ?";
                    PreparedStatement checkUserStmt = con.prepareStatement(checkUserSQL);
                    checkUserStmt.setString(1, username);
                    ResultSet rsUser = checkUserStmt.executeQuery();

                    if (rsUser.next()) {
                        JOptionPane.showMessageDialog(null, "Username sudah digunakan!", "Gagal", JOptionPane.ERROR_MESSAGE);
                        rsUser.close();
                        checkUserStmt.close();
                    } else {
                        rsUser.close();
                        checkUserStmt.close();

                        // Hash password
                        String hashedPassword = org.mindrot.jbcrypt.BCrypt.hashpw(password, org.mindrot.jbcrypt.BCrypt.gensalt());

                        query = "INSERT INTO pengguna_aplikasi(email, username, password, rfid_kode, role) VALUES(?, ?, ?, ?, ?)";
                        PreparedStatement ps = con.prepareStatement(query);
                        ps.setString(1, email);
                        ps.setString(2, username);
                        ps.setString(3, hashedPassword);
                        ps.setString(4, rfid);
                        ps.setString(5, role);
                        ps.executeUpdate();
                        ps.close();

                        EmailR.setText("");
                        UsernameR.setText("");
                        PasswordR.setText("");
                        RfidR.setText("");
                        RoleR.setSelectedIndex(0);

                        JOptionPane.showMessageDialog(null, "Account created successfully!");

                        // Pindah ke login
                        login lo = new login();
                        lo.setVisible(true);
                        lo.pack();
                        lo.setLocationRelativeTo(null);
                        dispose();
                    }
                }
            }
            con.close();
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }


    }//GEN-LAST:event_RegisterRActionPerformed

    private void EmailRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailRActionPerformed
        String email = EmailR.getText();
        if (!isValidEmail(email)) {

        }
    }//GEN-LAST:event_EmailRActionPerformed

    private void UsernameRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameRActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        login lg = new login();
        lg.setVisible(true);
        lg.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_loginBtnActionPerformed

    private void RoleRItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RoleRItemStateChanged

    }//GEN-LAST:event_RoleRItemStateChanged

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            FlatArcOrangeIJTheme.setup();
            UIManager.put("Button.arc", 999);
            UIManager.put("defaultFont", new Font("Poppins", Font.BOLD, 14));
            UIManager.put("Component.innerFocusWidth", 1);
            UIManager.put("Button.innerFocusWidth", 1);
        } catch (Exception ex) {
            System.err.println("Gagal mengatur tema FlatLaf Arc Orange.");
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailR;
    private javax.swing.JLabel LemailR;
    private javax.swing.JLabel LpasswordR;
    private javax.swing.JLabel LregisterR;
    private javax.swing.JLabel LrfidR;
    private javax.swing.JLabel LroleR;
    private javax.swing.JLabel LsdhpunyaakunR;
    private javax.swing.JLabel LusernameR;
    private javax.swing.JPasswordField PasswordR;
    private javax.swing.JButton RegisterR;
    private javax.swing.JTextField RfidR;
    private javax.swing.JComboBox<String> RoleR;
    private java.awt.Label TothepageR;
    private javax.swing.JTextField UsernameR;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel paneldalamR;
    private javax.swing.JPanel panelluar1R;
    private javax.swing.JPanel panelluar2R;
    private java.awt.Label welcomeR;
    // End of variables declaration//GEN-END:variables
}
